name: Eslint

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - run: npm ci
      - run: npm run lint
